[project]
name = "aoc2024"
version = "0.0.1"
description = "Advent of Code attempts 2024"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["numpy>=2.1.3", "ruff>=0.8.1", "typer>=0.14.0"]

[tool.ruff.lint]
select = ["ALL"]
ignore = ["D", "COM812", "ISC001", "T201"]
